[package]
name = "aaska2"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6"
pulldown-cmark = "0.13"
syntect = { version = "5.3.0", features = [] }
maud = { version = "0.27.0" }
tracing = "0.1.44"
petgraph = "0.8.3"

salsa = { version = "0.25.2" }
