[package]
name = "aaska2"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6"
pulldown-cmark = "0.13"
pulldown-cmark-escape = "0.11"
syntect = { version = "5.3.0", features = [] }
maud = { version = "0.27.0" }
tracing = "0.1.44"
petgraph = "0.8.3"

notify-debouncer-mini = { features = ["crossbeam-channel"], version = "0.7.0" }
salsa = { version = "0.25.2" }
dashmap = "7.0.0-rc2"
crossbeam-channel = "0.5.15"
sha2 = "0.11.0-rc.4"
